#!/bin/bash
mkdir -p "${STEAMAPPDIR}" || true
echo ${STEAMAPPDIR}

# Download Updates

bash "${STEAMCMDDIR}/steamcmd.sh" +force_install_dir "${STEAMAPPDIR}" \
				+login anonymous \
				+app_update "${STEAMAPPID}" validate \
				+quit

sed -i -e "s/{{SERVER_SERVER_NAME}}/${PALWORLD_SERVER_NAME}/g" \
    -e "s/{{SERVER_SERVER_DESCRIPTION}}/${PALWORLD_SERVER_DESCRIPTION}/g" \
    -e "s/{{SERVER_ADMIN_PASSWORD}}/${PALWORLD_ADMIN_PASSWORD}/g" \
    -e "s/{{SERVER_SERVER_PASSWORD}}/${PALWORLD_SERVER_PASSWORD}/g" \
    -e "s/{{SERVER_PUBLIC_PORT}}/${PALWORLD_PUBLIC_PORT}/g" \
    -e "s/{{SERVER_PUBLIC_IP}}/${PALWORLD_PUBLIC_IP}/g" \
    -e "s/{{SERVER_RCON_ENABLED}}/${PALWORLD_RCON_ENABLED}/g" \
    -e "s/{{SERVER_RCON_PORT}}/${PALWORLD_RCON_PORT}/g" \
    -e "s/{{SERVER_REGION}}/${PALWORLD_REGION}/g" \
    -e "s/{{SERVER_B_USE_AUTH}}/${PALWORLD_B_USE_AUTH}/g" \
    -e "s/{{SERVER_BAN_LIST_URL}}/${PALWORLD_BAN_LIST_URL}/g" \
    -e "s/{{SERVER_COOP_PLAYER_MAX_NUM}}/${PALWORLD_COOP_PLAYER_MAX_NUM}/g" \
    -e "s/{{SERVER_SERVER_PLAYER_MAX_NUM}}/${PALWORLD_SERVER_PLAYER_MAX_NUM}/g" \
    -e "s/{{SERVER_DIFFICULTY}}/${PALWORLD_DIFFICULTY}/g" \
    -e "s/{{SERVER_DAY_TIME_SPEED_RATE}}/${PALWORLD_DAY_TIME_SPEED_RATE}/g" \
    -e "s/{{SERVER_NIGHT_TIME_SPEED_RATE}}/${PALWORLD_NIGHT_TIME_SPEED_RATE}/g" \
    -e "s/{{SERVER_EXP_RATE}}/${PALWORLD_EXP_RATE}/g" \
    -e "s/{{SERVER_PAL_CAPTURE_RATE}}/${PALWORLD_PAL_CAPTURE_RATE}/g" \
    -e "s/{{SERVER_PAL_SPAWN_NUM_RATE}}/${PALWORLD_PAL_SPAWN_NUM_RATE}/g" \
    -e "s/{{SERVER_PAL_DAMAGE_RATE_ATTACK}}/${PALWORLD_PAL_DAMAGE_RATE_ATTACK}/g" \
    -e "s/{{SERVER_PAL_DAMAGE_RATE_DEFENSE}}/${PALWORLD_PAL_DAMAGE_RATE_DEFENSE}/g" \
    -e "s/{{SERVER_PLAYER_DAMAGE_RATE_ATTACK}}/${PALWORLD_PLAYER_DAMAGE_RATE_ATTACK}/g" \
    -e "s/{{SERVER_PLAYER_DAMAGE_RATE_DEFENSE}}/${PALWORLD_PLAYER_DAMAGE_RATE_DEFENSE}/g" \
    -e "s/{{SERVER_PLAYER_STOMACH_DECREACE_RATE}}/${PALWORLD_PLAYER_STOMACH_DECREACE_RATE}/g" \
    -e "s/{{SERVER_PLAYER_STAMINA_DECREACE_RATE}}/${PALWORLD_PLAYER_STAMINA_DECREACE_RATE}/g" \
    -e "s/{{SERVER_PLAYER_AUTO_HP_REGENE_RATE}}/${PALWORLD_PLAYER_AUTO_HP_REGENE_RATE}/g" \
    -e "s/{{SERVER_PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP}}/${PALWORLD_PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP}/g" \
    -e "s/{{SERVER_PAL_STOMACH_DECREACE_RATE}}/${PALWORLD_PAL_STOMACH_DECREACE_RATE}/g" \
    -e "s/{{SERVER_PAL_STAMINA_DECREACE_RATE}}/${PALWORLD_PAL_STAMINA_DECREACE_RATE}/g" \
    -e "s/{{SERVER_PAL_AUTO_HP_REGENE_RATE}}/${PALWORLD_PAL_AUTO_HP_REGENE_RATE}/g" \
    -e "s/{{SERVER_PAL_AUTO_HP_REGENE_RATE_IN_SLEEP}}/${PALWORLD_PAL_AUTO_HP_REGENE_RATE_IN_SLEEP}/g" \
    -e "s/{{SERVER_BUILD_OBJECT_DAMAGE_RATE}}/${PALWORLD_BUILD_OBJECT_DAMAGE_RATE}/g" \
    -e "s/{{SERVER_BUILD_OBJECT_DETERIORATION_DAMAGE_RATE}}/${PALWORLD_BUILD_OBJECT_DETERIORATION_DAMAGE_RATE}/g" \
    -e "s/{{SERVER_COLLECTION_DROP_RATE}}/${PALWORLD_COLLECTION_DROP_RATE}/g" \
    -e "s/{{SERVER_COLLECTION_OBJECT_HP_RATE}}/${PALWORLD_COLLECTION_OBJECT_HP_RATE}/g" \
    -e "s/{{SERVER_COLLECTION_OBJECT_RESPAWN_SPEED_RATE}}/${PALWORLD_COLLECTION_OBJECT_RESPAWN_SPEED_RATE}/g" \
    -e "s/{{SERVER_ENEMY_DROP_ITEM_RATE}}/${PALWORLD_ENEMY_DROP_ITEM_RATE}/g" \
    -e "s/{{SERVER_DEATH_PENALTY}}/${PALWORLD_DEATH_PENALTY}/g" \
    -e "s/{{SERVER_B_ENABLE_PLAYER_TO_PLAYER_DAMAGE}}/${PALWORLD_B_ENABLE_PLAYER_TO_PLAYER_DAMAGE}/g" \
    -e "s/{{SERVER_B_ENABLE_FRIENDLY_FIRE}}/${PALWORLD_B_ENABLE_FRIENDLY_FIRE}/g" \
    -e "s/{{SERVER_B_ENABLE_INVADER_ENEMY}}/${PALWORLD_B_ENABLE_INVADER_ENEMY}/g" \
    -e "s/{{SERVER_B_ACTIVE_UNKO}}/${PALWORLD_B_ACTIVE_UNKO}/g" \
    -e "s/{{SERVER_B_ENABLE_AIM_ASSIST_PAD}}/${PALWORLD_B_ENABLE_AIM_ASSIST_PAD}/g" \
    -e "s/{{SERVER_B_ENABLE_AIM_ASSIST_KEYBOARD}}/${PALWORLD_B_ENABLE_AIM_ASSIST_KEYBOARD}/g" \
    -e "s/{{SERVER_DROP_ITEM_MAX_NUM}}/${PALWORLD_DROP_ITEM_MAX_NUM}/g" \
    -e "s/{{SERVER_DROP_ITEM_MAX_NUM_UNKO}}/${PALWORLD_DROP_ITEM_MAX_NUM_UNKO}/g" \
    -e "s/{{SERVER_BASE_CAMP_MAX_NUM}}/${PALWORLD_BASE_CAMP_MAX_NUM}/g" \
    -e "s/{{SERVER_BASE_CAMP_WORKER_MAX_NUM}}/${PALWORLD_BASE_CAMP_WORKER_MAX_NUM}/g" \
    -e "s/{{SERVER_DROP_ITEM_ALIVE_MAX_HOURS}}/${PALWORLD_DROP_ITEM_ALIVE_MAX_HOURS}/g" \
    -e "s/{{SERVER_B_AUTO_RESET_GUILD_NO_ONLINE_PLAYERS}}/${PALWORLD_B_AUTO_RESET_GUILD_NO_ONLINE_PLAYERS}/g" \
    -e "s/{{SERVER_AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS}}/${PALWORLD_AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS}/g" \
    -e "s/{{SERVER_GUILD_PLAYER_MAX_NUM}}/${PALWORLD_GUILD_PLAYER_MAX_NUM}/g" \
    -e "s/{{SERVER_PAL_EGG_DEFAULT_HATCHING_TIME}}/${PALWORLD_PAL_EGG_DEFAULT_HATCHING_TIME}/g" \
    -e "s/{{SERVER_WORK_SPEED_RATE}}/${PALWORLD_WORK_SPEED_RATE}/g" \
    -e "s/{{SERVER_B_IS_MULTIPLAY}}/${PALWORLD_B_IS_MULTIPLAY}/g" \
    -e "s/{{SERVER_B_IS_PVP}}/${PALWORLD_B_IS_PVP}/g" \
    -e "s/{{SERVER_B_CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP}}/${PALWORLD_B_CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP}/g" \
    -e "s/{{SERVER_B_ENABLE_NON_LOGIN_PENALTY}}/${PALWORLD_B_ENABLE_NON_LOGIN_PENALTY}/g" \
    -e "s/{{SERVER_B_ENABLE_FAST_TRAVEL}}/${PALWORLD_B_ENABLE_FAST_TRAVEL}/g" \
    -e "s/{{SERVER_B_IS_START_LOCATION_SELECT_BY_MAP}}/${PALWORLD_B_IS_START_LOCATION_SELECT_BY_MAP}/g" \
    -e "s/{{SERVER_B_EXIST_PLAYER_AFTER_LOGOUT}}/${PALWORLD_B_EXIST_PLAYER_AFTER_LOGOUT}/g" \
    -e "s/{{SERVER_B_ENABLE_DEFENSE_OTHER_GUILD_PLAYER}}/${PALWORLD_B_ENABLE_DEFENSE_OTHER_GUILD_PLAYER}/g" \
    "${STEAMAPPDIR}/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini"

# Switch to server directory
cd "${STEAMAPPDIR}"

echo $(ls)

# Start Server
./PalServer.sh "${PALWORLD_ADDITIONAL_ARGS}"